baseURL = "https://tommyeriksen.dk"
title = "tommyeriksen.dk"
theme = "hugo-theme-m10c"

[pagination]
  pagerSize = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Tommy Eriksen"
  description = "Geek at heart"
  menu_item_separator = " - "
  avatar = "avatar.png"
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/tn8or"
  [[params.social]]
    icon = "brand-bluesky"
    name = "bluesky"
    url = "https://bsky.app/profile/tommyeriksen.dk"
  [[params.social]]
    icon = "brand-linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/toeriksen/"
  [[params.social]]
    icon = "brand-facebook"
    name = "facebook"
    url = "https://www.facebook.com/tommy.eriksen"

  # Default theme
  # [params.style]
  #   darkestColor = "#242930"
  #   darkColor = "#353b43"
  #   lightColor = "#afbac4"
  #   lightestColor = "#ffffff"
  #   primaryColor = "#57cc8a"

  # Green theme
  # [params.style]
  #   darkestColor = "#315659"
  #   darkColor = "#253031"
  #   lightColor = "#96a879"
  #   lightestColor = "#fff"
  #   primaryColor = "#dad865"
# Blue theme
[params.style]
    darkestColor = "#2a3149"
    darkColor = "#3d4563"
    lightColor = "#8b92a9"
    lightestColor = "#ffffff"
    primaryColor = "#0d6efd"
  # Red theme
  # [params.style]
  #   darkestColor = "#d35050"
  #   darkColor = "#212121"
  #   lightColor = "#d6d6d6"
  #   lightestColor = "#d3d3d3"
  #   primaryColor = "#ffffff"